const BASE_URI = 'http://localhost:5000';
const API_EXTENSION = '/api/v0';

const QUESTIONS_ENDPOINT = '/questions';
const REPORT_ENDPOINT = '/report';
const RESPONSE_ENDPOINT = '/response';

const QUESTIONS_URI = BASE_URI + API_EXTENSION + QUESTIONS_ENDPOINT;
const REPORT_URI = BASE_URI + API_EXTENSION + REPORT_ENDPOINT;
const RESPONSE_URI = BASE_URI + API_EXTENSION + RESPONSE_ENDPOINT;

export { QUESTIONS_URI, REPORT_URI, RESPONSE_URI };